// Additional blog articles content - Part 2
// Import this into the main articles file

export const additionalArticles = {
    'invitatii-nunta-rustica': {
        title: 'Invitații pentru Nunți Rustice: Idei și Inspirație',
        date: '18 Ianuarie 2026',
        readTime: '5 min',
        category: 'Stiluri',
        image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1200&auto=format&fit=crop',
        content: [
            'Nuntile rustice au un farmec aparte, combinând eleganța naturală cu căldura tradițională. Invitațiile tale trebuie să reflecte perfect această atmosferă.',
            '## Caracteristicile Stilului Rustic',
            'Stilul rustic se caracterizează prin:',
            '- Elemente naturale (lemn, pânză, flori sălbatice)',
            '- Culori pământii (maro, bej, verde oliv, alb)',
            '- Texturi organice',
            '- Simplitate elegantă',
            '## Elemente de Design pentru Invitații Rustice',
            '### Palete de Culori',
            '- **Clasic Rustic**: Maro, bej, alb crem',
            '- **Rustic Romantic**: Roz pudră, lavandă, verde mentă',
            '- **Rustic Modern**: Gri închis, alb, accente aurii',
            '### Tipografie',
            'Alege fonturi care evocă natura:',
            '- Fonturi script pentru nume',
            '- Fonturi serif pentru text principal',
            '- Evită fonturile prea moderne sau geometrice',
            '## Template-uri Digitale Rustice',
            'InvitOnline oferă template-uri special create pentru nunți rustice:',
            '- Fundal cu textură de lemn',
            '- Elemente florale ilustrate',
            '- Animații subtile de frunze',
            '## Personalizare Rustică',
            '### Imagini de Fundal',
            '- Fotografii cu peisaje naturale',
            '- Texturi de lemn sau pânză',
            '- Flori de câmp',
            '### Detalii Decorative',
            '- Ramuri și frunze ilustrate',
            '- Panglici virtuale',
            '- Sigilii cu ceară (digitale)',
            '## Textul Invitației',
            'Pentru o nuntă rustică, tonul trebuie să fie:',
            '- Cald și primitor',
            '- Simplu dar elegant',
            '- Autentic și personal',
            'Exemplu: "Sub cerul liber și înconjurați de natură, vă invităm să celebrați alături de noi începutul călătoriei noastre."',
            '## Combinații Perfecte',
            '### Rustic + Boho',
            'Adaugă elemente boho pentru un stil mai relaxat:',
            '- Pene',
            '- Dreamcatchere',
            '- Motive geometrice subtile',
            '### Rustic + Elegant',
            'Pentru o nuntă rustică dar rafinată:',
            '- Accente aurii',
            '- Tipografie elegantă',
            '- Detalii delicate',
            '## Concluzie',
            'Invitațiile rustice digitale oferă toate avantajele stilului tradițional, cu flexibilitatea și economia platformelor moderne. Poți crea o invitație care să capteze perfect esența nunții tale în natură.'
        ],
        relatedLinks: [
            { text: 'Vezi Template-uri Rustice', href: '/demo' },
            { text: 'Creează Invitația Rustică', href: '/create' }
        ]
    },
    'invitatii-botez-digitale': {
        title: 'Invitații Digitale pentru Botez: Ghid Complet',
        date: '14 Ianuarie 2026',
        readTime: '7 min',
        category: 'Botez',
        image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1200&auto=format&fit=crop',
        content: [
            'Botezul este unul dintre cele mai importante evenimente din viața unui copil. Invitațiile digitale oferă o modalitate modernă și practică de a anunța acest moment special.',
            '## De Ce Invitații Digitale pentru Botez?',
            '### Avantaje Specifice',
            '- **Rapiditate**: Trimite invitații instant, chiar și cu o săptămână înainte',
            '- **Flexibilitate**: Modifică detaliile dacă ceva se schimbă',
            '- **Eco-friendly**: Perfect pentru părinți conștienți de mediu',
            '- **Buget redus**: Mai mulți bani pentru cadouri sau petrecere',
            '## Elemente Esențiale',
            'O invitație de botez trebuie să includă:',
            '- Numele complet al copilului',
            '- Data și ora botezului',
            '- Locația bisericii',
            '- Detalii despre petrecere (dacă este cazul)',
            '- Numele nașilor',
            '- RSVP și contact',
            '## Stiluri Populare',
            '### Clasic Tradițional',
            '- Culori pastel (albastru/roz)',
            '- Simboluri religioase (cruci, îngeri)',
            '- Tipografie elegantă',
            '### Modern Minimalist',
            '- Design curat și simplu',
            '- Culori neutre',
            '- Fotografii ale bebelușului',
            '### Playful și Colorat',
            '- Ilustrații vesele',
            '- Culori vibrante',
            '- Elemente interactive',
            '## Texte pentru Invitații de Botez',
            '### Formal',
            '"Cu bucurie în suflet vă invităm să fiți alături de noi la botezul fiicei/fiului nostru, [Nume], care va avea loc pe [Data] la [Locație]."',
            '### Casual',
            '"Micuțul/Micuța nostru/noastră primește numele de [Nume]! Vino să sărbătorim împreună pe [Data]!"',
            '### Cu Versuri',
            '"Un îngeraș s-a născut în familia noastră și acum primește binecuvântarea divină. Fii alături de noi la botezul lui [Nume]."',
            '## Personalizare Specială',
            '### Fotografii',
            '- Prima fotografie a bebelușului',
            '- Colaj cu momente speciale',
            '- Ecografie artistică',
            '### Detalii Interactive',
            '- Countdown până la botez',
            '- Galerie foto',
            '- Playlist cu cântece de leagăn',
            '## Informații Practice',
            '### Pentru Invitați',
            'Include detalii despre:',
            '- Dress code (dacă există)',
            '- Parcare disponibilă',
            '- Durata estimată',
            '- Meniu (pentru alergii)',
            '### Pentru Nași',
            'Trimite o invitație specială nașilor cu:',
            '- Rol și responsabilități',
            '- Program detaliat',
            '- Lista de lucruri necesare',
            '## Timeline Invitații Botez',
            '- **4-6 săptămâni înainte**: Trimite invitațiile',
            '- **2 săptămâni înainte**: Deadline RSVP',
            '- **1 săptămână înainte**: Reminder',
            '## Concluzie',
            'Invitațiile digitale pentru botez combină tradiția cu modernitatea, oferind o soluție practică și elegantă pentru acest eveniment special. Cu InvitOnline, poți crea invitații memorabile în câteva minute.'
        ],
        relatedLinks: [
            { text: 'Template-uri pentru Botez', href: '/demo' },
            { text: 'Creează Invitația de Botez', href: '/create' }
        ]
    },
    'culori-nunta-2026': {
        title: 'Tendințe Culori pentru Nunți 2026: Palete Complete',
        date: '11 Ianuarie 2026',
        readTime: '6 min',
        category: 'Design',
        image: 'https://images.unsplash.com/photo-1523438097201-512ae7d59c44?w=1200&auto=format&fit=crop',
        content: [
            'Culorile nunții tale setează atmosfera întregului eveniment. În 2026, tendințele combină eleganța clasică cu accente moderne și îndrăznețe.',
            '## Top 5 Palete de Culori 2026',
            '### 1. Sage Green & Terracotta',
            'Combinația perfectă pentru nunți rustice-elegante:',
            '- Verde salvie (principal)',
            '- Terracotta (accent)',
            '- Alb crem (neutru)',
            '- Auriu mat (detalii)',
            'Perfect pentru: Nunți în aer liber, vară-toamnă',
            '### 2. Dusty Blue & Mauve',
            'Romantism modern și sofisticat:',
            '- Albastru prăfuit (principal)',
            '- Mauve/mov pudră (secundar)',
            '- Gri argintiu (accent)',
            '- Alb (bază)',
            'Perfect pentru: Nunți elegante, primăvară-vară',
            '### 3. Burgundy & Gold',
            'Lux și dramă pentru nunți de seară:',
            '- Burgundy profund (principal)',
            '- Auriu strălucitor (accent)',
            '- Negru (detalii)',
            '- Alb fildeș (contrast)',
            'Perfect pentru: Nunți de toamnă-iarnă, evenimente formale',
            '### 4. Coral & Mint',
            'Prospețime și energie pentru nunți de vară:',
            '- Coral vibrant (principal)',
            '- Verde mentă (secundar)',
            '- Piersică (ton mediu)',
            '- Alb (bază)',
            'Perfect pentru: Nunți la mare, evenimente outdoor',
            '### 5. Monochrome Neutrals',
            'Eleganță minimalistă și atemporală:',
            '- Bej/Taupe (principal)',
            '- Alb crem (secundar)',
            '- Gri cald (accent)',
            '- Auriu șampanie (detalii)',
            'Perfect pentru: Nunți moderne, orice sezon',
            '## Cum să Alegi Paleta Perfectă',
            '### Consideră Sezonul',
            '- **Primăvară**: Pasteluri, verde mentă, roz pudră',
            '- **Vară**: Culori vibrante, coral, turcoaz',
            '- **Toamnă**: Tonuri calde, burgundy, portocaliu ars',
            '- **Iarnă**: Albastru navy, argintiu, alb',
            '### Ține Cont de Locație',
            '- **Interior elegant**: Culori profunde, auriu',
            '- **Grădină**: Verde, floral, pasteluri',
            '- **Plajă**: Albastru, turcoaz, alb',
            '- **Rustic**: Maro, verde oliv, crem',
            '## Integrarea Culorilor în Invitații',
            '### Design Digital',
            'Cu InvitOnline poți:',
            '- Personaliza culorile oricărui template',
            '- Testa combinații diferite instant',
            '- Vedea preview în timp real',
            '- Schimba culorile oricând',
            '### Elemente de Culoare',
            '- **Fundal**: Culoarea principală sau neutră',
            '- **Text**: Contrast puternic pentru lizibilitate',
            '- **Accente**: Butoane, linii decorative',
            '- **Detalii**: Icoane, ilustrații',
            '## Psihologia Culorilor',
            '### Roșu/Burgundy',
            'Pasiune, energie, dramă - perfect pentru nunți romantice',
            '### Albastru',
            'Calm, încredere, eleganță - ideal pentru nunți formale',
            '### Verde',
            'Natură, prospețime, armonie - excelent pentru nunți eco',
            '### Roz',
            'Romantism, feminitate, dulceață - clasic pentru nunți',
            '### Auriu',
            'Lux, celebrare, căldură - adaugă strălucire oricărei palete',
            '## Greșeli de Evitat',
            '- **Prea multe culori**: Limitează-te la 3-4 culori principale',
            '- **Contrast slab**: Asigură-te că textul se citește ușor',
            '- **Ignorarea sezonului**: Culorile de iarnă nu funcționează vara',
            '- **Tendințe extreme**: Alege ceva care îți place cu adevărat',
            '## Concluzie',
            'Paleta de culori perfectă reflectă personalitatea voastră și creează atmosfera dorită. Cu invitații digitale, poți experimenta nelimitat până găsești combinația ideală.'
        ],
        relatedLinks: [
            { text: 'Testează Palete de Culori', href: '/create' },
            { text: 'Vezi Template-uri Colorate', href: '/demo' }
        ]
    },
    'invitatii-nunta-iarna': {
        title: 'Invitații pentru Nunți de Iarnă: Magia Sezonului Rece',
        date: '9 Ianuarie 2026',
        readTime: '5 min',
        category: 'Sezonal',
        image: 'https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=1200&auto=format&fit=crop',
        content: [
            'Nuntile de iarnă au un farmec magic aparte. Invitațiile tale trebuie să capteze această atmosferă de basm și să pregătească invitații pentru o celebrare de neuitat.',
            '## Caracteristicile Nuntilor de Iarnă',
            'Sezonul rece oferă oportunități unice:',
            '- Atmosferă intimă și caldă',
            '- Decorațiuni festive naturale',
            '- Lumini și lumânări',
            '- Eleganță rafinată',
            '## Palete de Culori pentru Iarnă',
            '### Clasic Iarnă',
            '- Alb și argintiu',
            '- Albastru navy și auriu',
            '- Roșu burgundy și verde smarald',
            '### Modern Iarnă',
            '- Gri închis și roz pudră',
            '- Albastru prăfuit și auriu șampanie',
            '- Negru și alb cu accente metalice',
            '### Festiv',
            '- Roșu și verde (pentru nunți de Crăciun)',
            '- Argintiu și albastru glacial',
            '- Auriu și alb fildeș',
            '## Elemente de Design',
            '### Motive Sezoniere',
            '- Fulgi de nea (animați în versiunea digitală)',
            '- Ramuri de brad',
            '- Cristale de gheață',
            '- Lumânări și lumini',
            '### Texturi',
            '- Efect de sclipire (glitter)',
            '- Fundal cu textura zăpezii',
            '- Elemente metalice',
            '- Transparențe glaciale',
            '## Textul Invitației',
            '### Romantic de Iarnă',
            '"Sub cerul înstelat al iernii, ne unim destinele. Alătură-te nouă pentru o seară magică de celebrare."',
            '### Festiv',
            '"Căldura iubirii noastre învinge frigul iernii! Vino să sărbătorim împreună în cea mai frumoasă seară de iarnă."',
            '### Elegant',
            '"În eleganța sezonului de iarnă, vă invităm să fiți martori ai începutului călătoriei noastre veșnice."',
            '## Considerații Practice',
            '### Informații Esențiale',
            'Pentru nunți de iarnă, include:',
            '- **Vreme**: Menționează că evenimentul este interior',
            '- **Dress code**: Sugerează ținute calde pentru exterior',
            '- **Transport**: Detalii despre parcare și acces în caz de ninsoare',
            '- **Cazare**: Recomandări pentru invitați din alte orașe',
            '### Timing',
            '- Evită perioada 24-26 decembrie (Crăciun)',
            '- Evită Revelion (31 decembrie - 1 ianuarie)',
            '- Ideal: Ianuarie-februarie sau decembrie (înainte de 20)',
            '## Avantajele Invitațiilor Digitale pentru Iarnă',
            '### Animații Speciale',
            '- Fulgi de nea care cad',
            '- Lumini strălucitoare',
            '- Tranziții glaciale',
            '- Efecte de sclipire',
            '### Flexibilitate',
            '- Modificări rapide dacă vremea afectează planurile',
            '- Update-uri instant pentru invitați',
            '- Reminder-e automate',
            '## Inspirație Tematică',
            '### Winter Wonderland',
            'Tema clasică de basm de iarnă:',
            '- Alb predominant',
            '- Argintiu și albastru glacial',
            '- Cristale și fulgi',
            '### Rustic Winter',
            'Căldură și confort:',
            '- Maro și bej',
            '- Verde brad',
            '- Texturi de lemn',
            '### Glamorous Winter',
            'Lux și strălucire:',
            '- Negru și auriu',
            '- Detalii metalice',
            '- Eleganță maximă',
            '## Detalii Interactive',
            'Pentru invitații digitale de iarnă:',
            '- **Countdown cu tema iernii**: Zile până la nuntă cu fulgi',
            '- **Playlist de iarnă**: Melodii romantice de sezon',
            '- **Galerie foto**: Poze de cuplu în peisaje de iarnă',
            '- **Hartă interactivă**: Cu avertizări despre vreme',
            '## Concluzie',
            'Nuntile de iarnă oferă oportunități unice pentru invitații memorabile. Cu template-uri digitale, poți crea o invitație care captează perfect magia sezonului rece.'
        ],
        relatedLinks: [
            { text: 'Template-uri de Iarnă', href: '/demo' },
            { text: 'Creează Invitația de Iarnă', href: '/create' }
        ]
    },
    'qr-code-invitatii-nunta': {
        title: 'QR Code pe Invitații: Ghid Complet de Utilizare',
        date: '7 Ianuarie 2026',
        readTime: '4 min',
        category: 'Tehnologie',
        image: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=1200&auto=format&fit=crop',
        content: [
            'Codurile QR au transformat modul în care invitații interacționează cu invitațiile de nuntă. Iată cum să le folosești eficient pentru o experiență modernă și practică.',
            '## Ce Este un Cod QR?',
            'Un cod QR (Quick Response) este un cod de bare bidimensional care poate fi scanat cu camera telefonului pentru a accesa instant informații digitale.',
            '## Avantajele QR Codes pe Invitații',
            '### 1. Acces Instant',
            'Invitații pot scana și accesa:',
            '- Detalii complete ale evenimentului',
            '- Hartă și direcții',
            '- Formular RSVP',
            '- Website-ul nunții',
            '### 2. Actualizări în Timp Real',
            'Modifică informațiile fără a retrimite invitații:',
            '- Schimbări de program',
            '- Detalii de ultimă oră',
            '- Informații suplimentare',
            '### 3. Tracking și Analytics',
            'Vezi câți invitați au scanat codul:',
            '- Monitorizează engagement-ul',
            '- Identifică cine a accesat informațiile',
            '- Optimizează comunicarea',
            '## Utilizări Practice',
            '### RSVP Rapid',
            'Cel mai popular use case:',
            '- Scanează → Formular RSVP',
            '- Completează în 30 secunde',
            '- Confirmare automată',
            '### Direcții GPS',
            'Link direct către Google Maps:',
            '- Scanează → Hartă',
            '- Navigație instant',
            '- Zero confuzie',
            '### Website Nuntă',
            'Acces la toate informațiile:',
            '- Program detaliat',
            '- Galerie foto',
            '- Informații cazare',
            '- Registry cadouri',
            '### Add to Calendar',
            'Salvare automată în calendar:',
            '- Scanează → Event',
            '- Adaugă în Google/Apple Calendar',
            '- Reminder automat',
            '## Cum să Creezi QR Codes Eficiente',
            '### Design',
            '- **Dimensiune**: Minim 2x2 cm pentru scanare ușoară',
            '- **Contrast**: Fundal deschis, cod întunecat',
            '- **Spațiu**: Margine albă în jur',
            '- **Personalizare**: Logo în centru (opțional)',
            '### Plasare',
            'Unde să plasezi codul QR:',
            '- **Invitații digitale**: În footer sau secțiune RSVP',
            '- **Invitații printate**: Pe verso sau colț',
            '- **Save the Date**: Pentru detalii viitoare',
            '## Best Practices',
            '### 1. Testează Întotdeauna',
            'Înainte de trimitere:',
            '- Scanează cu multiple telefoane',
            '- Verifică pe iOS și Android',
            '- Testează în condiții diferite de lumină',
            '### 2. Oferă Alternative',
            'Nu toată lumea știe să scaneze:',
            '- Include și link text',
            '- Adaugă instrucțiuni scurte',
            '- Oferă opțiuni multiple',
            '### 3. URL Scurt și Memorabil',
            'Folosește URL shorteners:',
            '- bit.ly/nunta-maria-ion',
            '- Ușor de tastat manual',
            '- Professional',
            '## Securitate și Privacy',
            '### Protejează Datele',
            '- Nu include informații sensibile direct în QR',
            '- Folosește pagini protejate cu parolă pentru detalii private',
            '- Respectă GDPR pentru datele invitaților',
            '### Link-uri Sigure',
            '- Folosește HTTPS',
            '- Evită link-uri suspecte',
            '- Verifică destinația',
            '## Integrare cu InvitOnline',
            'Platforma noastră oferă:',
            '- **Generare automată**: QR code pentru fiecare invitație',
            '- **Personalizare**: Culori și stil adaptat designului',
            '- **Analytics**: Tracking complet al scanărilor',
            '- **Dynamic QR**: Modifică destinația fără a schimba codul',
            '## Tendințe Viitoare',
            '### QR Codes Interactive',
            '- Animații la scanare',
            '- Realitate augmentată',
            '- Gamification',
            '### Smart QR',
            '- Detectare automată a limbii',
            '- Personalizare bazată pe locație',
            '- Integrare AI',
            '## Concluzie',
            'Codurile QR transformă invitațiile statice în experiențe interactive. Sunt simple, eficiente și oferă o modalitate modernă de a gestiona comunicarea cu invitații.'
        ],
        relatedLinks: [
            { text: 'Generează QR Code', href: '/create' },
            { text: 'Vezi Demo Interactive', href: '/demo' }
        ]
    },
    'invitatii-nunta-la-mare': {
        title: 'Invitații pentru Nunți la Mare: Stil Beach Wedding',
        date: '4 Ianuarie 2026',
        readTime: '6 min',
        category: 'Destinații',
        image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&auto=format&fit=crop',
        content: [
            'Nuntile la mare au un farmec special - combinația dintre romantism, relaxare și aventură. Invitațiile tale trebuie să capteze această atmosferă unică.',
            '## Esența Beach Wedding',
            'Caracteristicile unei nunți la mare:',
            '- Atmosferă relaxată și informală',
            '- Conexiune cu natura',
            '- Culori inspirate din ocean',
            '- Eleganță simplă',
            '## Palete de Culori Nautice',
            '### Clasic Nautic',
            '- Albastru navy și alb',
            '- Roșu și alb (stil ancora)',
            '- Accente aurii (nisip)',
            '### Tropical Vibrant',
            '- Turcoaz și coral',
            '- Verde mentă și roz',
            '- Galben și albastru cerulean',
            '### Sunset Romance',
            '- Portocaliu și roz',
            '- Violet și auriu',
            '- Piersică și lavandă',
            '### Neutral Beach',
            '- Bej nisip și alb',
            '- Gri deschis și albastru pal',
            '- Crem și turcoaz pastel',
            '## Elemente de Design',
            '### Motive Maritime',
            '- Valuri și ape',
            '- Scoici și stele de mare',
            '- Ancora și corzi',
            '- Palmieri și frunze tropicale',
            '### Texturi',
            '- Efect de nisip',
            '- Ape transparente',
            '- Lemn îmbătrânit',
            '- Pânză de in',
            '## Stiluri de Invitații',
            '### Boarding Pass',
            'Perfect pentru destinații exotice:',
            '- Design de bilet de avion',
            '- Detalii despre călătorie',
            '- Informații despre destinație',
            '### Message in a Bottle',
            'Romantic și tematic:',
            '- Sticlă virtuală cu mesaj',
            '- Animație de deschidere',
            '- Harta comorii către locație',
            '### Minimalist Beach',
            'Elegant și simplu:',
            '- Fotografii cu ocean',
            '- Tipografie curată',
            '- Culori pastel',
            '## Textul Invitației',
            '### Romantic',
            '"Unde valurile întâlnesc nisipul și soarele sărută marea, ne vom uni destinele. Alătură-te nouă pentru o celebrare la malul oceanului."',
            '### Casual',
            '"Scoate sandalele și pregătește-te pentru petrecere! Ne căsătorim pe plajă și vrem să fii acolo!"',
            '### Aventuros',
            '"Aventura noastră începe unde pământul se termină. Hai cu noi la mare pentru nunta vieții!"',
            '## Informații Practice Esențiale',
            '### Pentru Invitați',
            'Include detalii despre:',
            '- **Dress code**: "Beach formal" sau "Casual elegant"',
            '- **Încălțăminte**: Sugerează sandale sau barefoot',
            '- **Protecție solară**: Recomandă cremă și pălării',
            '- **Vreme**: Menționează plan B pentru ploaie',
            '### Logistică',
            '- **Transport**: De la hotel la plajă',
            '- **Parcare**: Unde pot parca invitații',
            '- **Cazare**: Recomandări de hoteluri',
            '- **Activități**: Ce pot face înainte/după',
            '## Considerații Speciale',
            '### Timing',
            '- **Evită orele de vârf**: 12-16 (prea cald)',
            '- **Ideal**: Sunset (18-20) sau dimineață (9-11)',
            '- **Sezon**: Iunie-septembrie (România)',
            '### Permise',
            '- Verifică dacă e nevoie de permis pentru plajă',
            '- Informează autoritățile locale',
            '- Respectă regulile plajei',
            '## Elemente Interactive Digitale',
            '### Hartă Interactivă',
            '- Locația exactă pe plajă',
            '- Puncte de interes apropiate',
            '- Direcții de la hotel',
            '### Countdown cu Tema Mării',
            '- Valuri animate',
            '- Zile până la nuntă',
            '- Prognoza meteo',
            '### Playlist Beach',
            '- Melodii de vară',
            '- Muzică relaxantă',
            '- Sugestii de la invitați',
            '## Sfaturi de Design',
            '### Fotografii',
            '- Poze de cuplu pe plajă',
            '- Sunset romantic',
            '- Detalii maritime',
            '### Animații',
            '- Valuri care se mișcă',
            '- Păsări zburând',
            '- Soare răsărind/apunând',
            '### Fonturi',
            '- Script pentru romantism',
            '- Sans-serif pentru claritate',
            '- Evită fonturile prea formale',
            '## Concluzie',
            'Invitațiile pentru nunți la mare trebuie să transmită relaxare, romantism și aventură. Cu template-uri digitale, poți crea perfect această atmosferă și să pregătești invitații pentru o experiență de neuitat.'
        ],
        relatedLinks: [
            { text: 'Template-uri Beach Wedding', href: '/demo' },
            { text: 'Creează Invitația ta de Plajă', href: '/create' }
        ]
    },
    'save-the-date-vs-invitatie': {
        title: 'Save the Date vs Invitație: Diferențe și Când să Trimiți',
        date: '2 Ianuarie 2026',
        readTime: '5 min',
        category: 'Planificare',
        image: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=1200&auto=format&fit=crop',
        content: [
            'Multe cupluri se întreabă dacă au nevoie atât de Save the Date cât și de invitație oficială. Iată tot ce trebuie să știi despre diferențe și când să folosești fiecare.',
            '## Ce Este Save the Date?',
            'Save the Date este un anunț preliminar care:',
            '- Informează invitații despre data nunții',
            '- Se trimite cu mult timp înainte',
            '- Nu include toate detaliile',
            '- Nu necesită RSVP',
            '## Ce Este Invitația Oficială?',
            'Invitația oficială este documentul complet care:',
            '- Include toate detaliile evenimentului',
            '- Se trimite mai aproape de dată',
            '- Necesită confirmare (RSVP)',
            '- Este mai formală și detaliată',
            '## Diferențe Cheie',
            '### Conținut',
            '**Save the Date include:**',
            '- Numele mirilor',
            '- Data nunții',
            '- Orașul/Locația generală',
            '- "Invitație formală urmează"',
            '**Invitația include:**',
            '- Toate detaliile de mai sus PLUS:',
            '- Ora exactă',
            '- Adresa completă',
            '- Dress code',
            '- RSVP deadline',
            '- Informații despre cazare/transport',
            '### Timing',
            '**Save the Date:**',
            '- 6-12 luni înainte (nunți locale)',
            '- 9-12 luni înainte (nunți destinate)',
            '**Invitația:**',
            '- 6-8 săptămâni înainte (nunți locale)',
            '- 3 luni înainte (nunți destinate)',
            '### Stil și Ton',
            '**Save the Date:**',
            '- Mai casual și playful',
            '- Poate fi creativ și neconvențional',
            '- Focus pe anunț, nu pe detalii',
            '**Invitația:**',
            '- Mai formală și elegantă',
            '- Trebuie să reflecte stilul nunții',
            '- Completă și profesională',
            '## Ai Nevoie de Ambele?',
            '### DA, dacă:',
            '- Nunta este într-o destinație îndepărtată',
            '- Mulți invitați trebuie să călătorească',
            '- Data este în sezon aglomerat (vară)',
            '- Lista de invitați este mare (150+)',
            '- Vrei să dai timp invitaților să planifice',
            '### NU, dacă:',
            '- Nunta este intimă (sub 50 invitați)',
            '- Majoritatea invitaților sunt locali',
            '- Ai timp limitat (sub 6 luni până la nuntă)',
            '- Buget restrâns',
            '- Preferi simplitate',
            '## Avantajele Save the Date',
            '### 1. Planificare Timpurie',
            'Invitații pot:',
            '- Rezerva concediu',
            '- Planifica bugetul',
            '- Evita alte evenimente',
            '### 2. Flexibilitate',
            'Tu poți:',
            '- Finaliza detaliile mai târziu',
            '- Schimba locația (dacă e nevoie)',
            '- Ajusta lista de invitați',
            '### 3. Excitement Building',
            '- Creează anticipare',
            '- Începe conversația despre nuntă',
            '- Generează buzz',
            '## Cum să Creezi Save the Date Perfect',
            '### Conținut Esențial',
            '"Save the Date!',
            '[Numele Mirilor]',
            '[Data]',
            '[Oraș/Locație]',
            'Invitație formală urmează"',
            '### Design',
            '- Poate fi mai casual decât invitația',
            '- Include o fotografie de cuplu',
            '- Reflectă tema nunții (dacă știi)',
            '- Simplu dar memorabil',
            '## Digital vs. Printat',
            '### Save the Date Digital',
            'Avantaje:',
            '- Trimis instant',
            '- Cost zero',
            '- Ușor de actualizat',
            '- Eco-friendly',
            '### Invitație Digitală',
            'Avantaje:',
            '- RSVP automat',
            '- Tracking în timp real',
            '- Modificări posibile',
            '- Link către website',
            '## Timeline Complet',
            '### 12 Luni Înainte',
            '- Stabilește data și locația',
            '- Creează lista preliminară de invitați',
            '### 9-10 Luni Înainte',
            '- Trimite Save the Date',
            '- Începe să finalizezi detaliile',
            '### 3-4 Luni Înainte',
            '- Finalizează toate detaliile',
            '- Creează invitația oficială',
            '### 6-8 Săptămâni Înainte',
            '- Trimite invitațiile oficiale',
            '- Setează deadline RSVP',
            '### 3-4 Săptămâni Înainte',
            '- Deadline RSVP',
            '- Follow-up cu cei care nu au răspuns',
            '## Greșeli de Evitat',
            '### La Save the Date',
            '- Nu trimite dacă nu ești 100% sigur de dată',
            '- Nu include prea multe detalii',
            '- Nu uita să menționezi că urmează invitație',
            '### La Invitație',
            '- Nu schimba dramatic stilul față de Save the Date',
            '- Nu trimite prea târziu',
            '- Nu uita deadline-ul RSVP',
            '## Concluzie',
            'Save the Date și invitația oficială servesc scopuri diferite dar complementare. Cu InvitOnline, poți crea ambele digital, economisind timp și bani, păstrând flexibilitatea de a actualiza informațiile.'
        ],
        relatedLinks: [
            { text: 'Creează Save the Date', href: '/create' },
            { text: 'Vezi Template-uri', href: '/demo' }
        ]
    },
    'invitatii-nunta-eleganta': {
        title: 'Invitații pentru Nunți Elegante: Rafinament și Lux',
        date: '30 Decembrie 2025',
        readTime: '7 min',
        category: 'Lux',
        image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop',
        content: [
            'Nuntile elegante necesită invitații care să reflecte rafinamentul și luxul evenimentului. Iată cum să creezi invitații care impresionează de la prima privire.',
            '## Esența Eleganței',
            'O invitație elegantă se caracterizează prin:',
            '- Simplitate sofisticată',
            '- Atenție la detalii',
            '- Materiale premium (sau aspect premium)',
            '- Tipografie rafinată',
            '- Echilibru perfect',
            '## Palete de Culori Elegante',
            '### Monochrome Clasic',
            '- Negru și alb',
            '- Gri antracit și alb fildeș',
            '- Navy profund și alb',
            '### Metalice Luxoase',
            '- Auriu și alb',
            '- Argintiu și gri',
            '- Rose gold și blush',
            '### Tonuri Profunde',
            '- Burgundy și auriu',
            '- Smarald și auriu',
            '- Albastru royal și argintiu',
            '## Tipografie Elegantă',
            '### Serif Clasic',
            'Pentru formalitate și tradiție:',
            '- Garamond',
            '- Baskerville',
            '- Didot',
            '### Script Rafinat',
            'Pentru romantism elegant:',
            '- Copperplate',
            '- Edwardian Script',
            '- Snell Roundhand',
            '### Sans-Serif Modern',
            'Pentru eleganță contemporană:',
            '- Futura',
            '- Helvetica Neue',
            '- Avenir',
            '## Elemente de Design',
            '### Minimalism Sofisticat',
            '- Spațiu alb generos',
            '- Linii curate',
            '- Focus pe conținut',
            '- Zero clutter',
            '### Detalii Luxoase',
            '- Monograme personalizate',
            '- Rame decorative subtile',
            '- Accente metalice',
            '- Ilustrații delicate',
            '### Ierarhie Vizuală',
            '- Nume-le mirilor dominant',
            '- Detalii secundare mai mici',
            '- Informații terțiare discrete',
            '## Formulări Elegante',
            '### Ultra Formal',
            '"Domnul și Doamna [Nume Părinți]',
            'au onoarea de a vă invita',
            'la cununia religioasă a fiicei lor',
            '[Nume Completă Mireasă]',
            'cu',
            '[Nume Complet Mire]',
            'fiul Domnului și Doamnei [Nume Părinți]"',
            '### Formal Modern',
            '"[Prenume] și [Prenume]',
            'vă invită cu deosebită plăcere',
            'să fiți martori ai unirii lor în căsătorie"',
            '### Elegant Simplu',
            '"Împreună cu familiile noastre,',
            'vă invităm să celebrați',
            'începutul călătoriei noastre"',
            '## Structura Perfectă',
            '### Secțiunea Principală',
            '- Numele mirilor (cel mai vizibil)',
            '- Invitația formală',
            '- Data și ora (format complet)',
            '- Locația (adresă completă)',
            '### Detalii Secundare',
            '- Dress code ("Black tie" sau "Formal attire")',
            '- Informații RSVP',
            '- Website nuntă (dacă există)',
            '### Informații Terțiare',
            '- Detalii cazare',
            '- Informații transport',
            '- Contact pentru întrebări',
            '## Dress Code pentru Nunți Elegante',
            '### Black Tie',
            'Cel mai formal:',
            '- Bărbați: Smoking',
            '- Femei: Rochie lungă',
            '### Black Tie Optional',
            'Formal dar flexibil:',
            '- Bărbați: Smoking sau costum întunecat',
            '- Femei: Rochie lungă sau cocktail elegantă',
            '### Formal / Cocktail Attire',
            'Elegant dar mai relaxat:',
            '- Bărbați: Costum întunecat',
            '- Femei: Rochie cocktail sau lungă',
            '## Detalii Interactive pentru Digital',
            '### Animații Subtile',
            '- Fade-in elegant',
            '- Tranziții smooth',
            '- Efecte de sclipire discretă',
            '- Hover effects rafinate',
            '### Elemente Premium',
            '- Video background cu mișcare lentă',
            '- Muzică clasică de fundal (opțional)',
            '- Galerie foto elegantă',
            '- Countdown sofisticat',
            '## Locații Elegante',
            'Invitația trebuie să se potrivească cu:',
            '- **Palate și conace**: Maxim formalitate',
            '- **Hoteluri 5 stele**: Lux modern',
            '- **Grădini botanice**: Eleganță naturală',
            '- **Muzee și galerii**: Sofisticare culturală',
            '## Greșeli de Evitat',
            '### Design',
            '- Prea multe fonturi (max 2-3)',
            '- Culori prea vibrante',
            '- Clipart sau imagini generice',
            '- Layout aglomerat',
            '### Conținut',
            '- Limbaj prea casual',
            '- Informații incomplete',
            '- Greșeli de ortografie',
            '- Formatare inconsistentă',
            '## Extras de Lux',
            'Pentru invitații cu adevărat speciale:',
            '- **Monogramă personalizată**: Design unic pentru cuplu',
            '- **Ilustrații custom**: Portrete sau locații',
            '- **Video invitație**: Mesaj personal de la miri',
            '- **Website dedicat**: Portal complet pentru invitați',
            '## Inspirație din Nunți Regale',
            'Învață de la cele mai elegante nunți:',
            '- Simplitate în design',
            '- Calitate peste cantitate',
            '- Atenție la protocol',
            '- Detalii impecabile',
            '## Concluzie',
            'Invitațiile elegante sunt despre echilibrul perfect între tradiție și modernitate, simplitate și lux. Cu InvitOnline, poți crea invitații digitale care rivalizează cu cele mai scumpe invitații printate, la o fracțiune din cost.'
        ],
        relatedLinks: [
            { text: 'Template-uri Premium', href: '/demo' },
            { text: 'Creează Invitația Elegantă', href: '/create' }
        ]
    }
}
